# See https://github.com/pypa/manylinux
FROM quay.io/pypa/manylinux_2_28_aarch64

ARG CUDA_VERSION
ARG CUDNN_VERSION

# Install cudnn and cuda toolkit
RUN dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/sbsa/cuda-rhel8.repo
RUN dnf clean all
RUN dnf -y module install nvidia-driver:native-dkms --skip-broken
RUN dnf -y install cuda-toolkit-${CUDA_VERSION}
RUN dnf -y install cudnn9-cuda-13
