variables:
  JFROG_API_KEY: $JFROG_API_KEY
  GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - cpp_tests
    - python_tests
    - pycudnnTest

.fetch_cudnn:template:
    before_script:
        - BASE_URL=https://urm.nvidia.com/artifactory/hw-cudnn-generic/CUDNN/v8.9_cuda_12.1/
        - LATEST_DATE_TIME=`curl -S $BASE_URL 2> /dev/null | grep "8.9.3" | grep href |  awk -F\  '{print $3, $4}' | sort -n -t- -k3,3 -k2,2M -k1,1n | tail -2 | head -1`
        - LATEST_VER=`curl -S $BASE_URL 2> /dev/null | grep "$LATEST_DATE_TIME" | awk -F'["/]' '{print $2}'`
        - echo ${LATEST_DATE_TIME} ${LATEST_VER} ${BASE_URL}${LATEST_VER}/debug_cudnn-linux-x86_64-${LATEST_VER}.tar.gz
        - wget -q --password ${JFROG_API_KEY} ${BASE_URL}${LATEST_VER}/debug_cudnn-linux-x86_64-${LATEST_VER}.tar.gz -O cudnn.tar.gz
        - tar xvf cudnn.tar.gz --directory /
        - export CUDNN_PATH=/debug_cudnn

.build:template:
    script:
        - ci/build.sh
    # keep the build directory so that later jobs can use it
    artifacts:
        paths:
            - build/
        expire_in: 1 week

.test:template:
    stage: cpp_tests
    script:
        - ci/run_cpp_tests.sh
    # Upload test report to gitlab
    artifacts:
        when: always
        reports:
            junit: build/result-junit.xml
        expire_in: 1 week

.pytest:template:
    stage: python_tests
    script:
        - ci/run_python_tests.sh

.pycudnntest:template:
    stage: pycudnnTest
    script:
        - ci/run_pycudnntest.sh

build:cudnn_8.6.0.163:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.6.0.163_torch
    stage: build
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere", "GA10x"]
    tags:
        - ${ARCH}
    extends: .build:template

test:cudnn_8.6.0.163:GA10x:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.6.0.163_torch
    extends: .test:template
    dependencies: ["build:cudnn_8.6.0.163: [GA10x]"]
    tags:
        - GA10x
    needs:
        - ["build:cudnn_8.6.0.163: [GA10x]"]

pytest:cudnn_8.6.0.163:GA10x:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.6.0.163_torch
    extends: .pytest:template
    dependencies: ["build:cudnn_8.6.0.163: [GA10x]"]
    tags:
        - GA10x
    needs:
        - ["build:cudnn_8.6.0.163: [GA10x]"]

pycudnntest:cudnn_8.6.0.163:GA10x:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.6.0.163_torch
    extends: .pycudnntest:template
    dependencies: ["build:cudnn_8.6.0.163: [GA10x]"]
    tags:
        - GA10x
    needs:
        - ["build:cudnn_8.6.0.163: [GA10x]"]

test:cudnn_8.6.0.163:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.6.0.163_torch
    extends: .test:template
    dependencies: ["build:cudnn_8.6.0.163: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.6.0.163: [Ampere]"]

pytest:cudnn_8.6.0.163:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.6.0.163_torch
    extends: .pytest:template
    dependencies: ["build:cudnn_8.6.0.163: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.6.0.163: [Ampere]"]

pycudnntest:cudnn_8.6.0.163:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.6.0.163_torch
    extends: .pycudnntest:template
    dependencies: ["build:cudnn_8.6.0.163: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.6.0.163: [Ampere]"]


test:cudnn_8.6.0.163:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.6.0.163_torch
    extends: .test:template
    dependencies: ["build:cudnn_8.6.0.163: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.6.0.163: [Hopper]"]

pytest:cudnn_8.6.0.163:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.6.0.163_torch
    extends: .pytest:template
    dependencies: ["build:cudnn_8.6.0.163: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.6.0.163: [Hopper]"]

pycudnntest:cudnn_8.6.0.163:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.6.0.163_torch
    extends: .pycudnntest:template
    dependencies: ["build:cudnn_8.6.0.163: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.6.0.163: [Hopper]"]


build:cudnn_8.7.0.84:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.7.0.84_torch
    stage: build
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere", "GA10x"]
    tags:
        - ${ARCH}
    extends: .build:template

test:cudnn_8.7.0.84:GA10x:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.7.0.84_torch
    extends: .test:template
    dependencies: ["build:cudnn_8.7.0.84: [GA10x]"]
    tags:
        - GA10x
    needs:
        - ["build:cudnn_8.7.0.84: [GA10x]"]

pytest:cudnn_8.7.0.84:GA10x:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.7.0.84_torch
    extends: .pytest:template
    dependencies: ["build:cudnn_8.7.0.84: [GA10x]"]
    tags:
        - GA10x
    needs:
        - ["build:cudnn_8.7.0.84: [GA10x]"]

pycudnntest:cudnn_8.7.0.84:GA10x:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.7.0.84_torch
    extends: .pycudnntest:template
    dependencies: ["build:cudnn_8.7.0.84: [GA10x]"]
    tags:
        - GA10x
    needs:
        - ["build:cudnn_8.7.0.84: [GA10x]"]

test:cudnn_8.7.0.84:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.7.0.84_torch
    extends: .test:template
    dependencies: ["build:cudnn_8.7.0.84: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.7.0.84: [Ampere]"]

pytest:cudnn_8.7.0.84:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.7.0.84_torch
    extends: .pytest:template
    dependencies: ["build:cudnn_8.7.0.84: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.7.0.84: [Ampere]"]

pycudnntest:cudnn_8.7.0.84:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.7.0.84_torch
    extends: .pycudnntest:template
    dependencies: ["build:cudnn_8.7.0.84: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.7.0.84: [Ampere]"]

test:cudnn_8.7.0.84:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.7.0.84_torch
    extends: .test:template
    dependencies: ["build:cudnn_8.7.0.84: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.7.0.84: [Hopper]"]

pytest:cudnn_8.7.0.84:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.7.0.84_torch
    extends: .pytest:template
    dependencies: ["build:cudnn_8.7.0.84: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.7.0.84: [Hopper]"]

pycudnntest:cudnn_8.7.0.84:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_11.8_cudnn_8.7.0.84_torch
    extends: .pycudnntest:template
    dependencies: ["build:cudnn_8.7.0.84: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.7.0.84: [Hopper]"]

build:cudnn_8.8.0.121:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.0_cudnn_8.8.0.121_torch
    stage: build
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends: .build:template

test:cudnn_8.8.0.121:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.0_cudnn_8.8.0.121_torch
    extends: .test:template
    dependencies: ["build:cudnn_8.8.0.121: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.8.0.121: [Ampere]"]

pytest:cudnn_8.8.0.121:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.0_cudnn_8.8.0.121_torch
    extends: .pytest:template
    dependencies: ["build:cudnn_8.8.0.121: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.8.0.121: [Ampere]"]

pycudnntest:cudnn_8.8.0.121:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.0_cudnn_8.8.0.121_torch
    extends: .pycudnntest:template
    dependencies: ["build:cudnn_8.8.0.121: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.8.0.121: [Ampere]"]

test:cudnn_8.8.0.121:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.0_cudnn_8.8.0.121_torch
    extends: .test:template
    dependencies: ["build:cudnn_8.8.0.121: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.8.0.121: [Hopper]"]

pytest:cudnn_8.8.0.121:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.0_cudnn_8.8.0.121_torch
    extends: .pytest:template
    dependencies: ["build:cudnn_8.8.0.121: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.8.0.121: [Hopper]"]

pycudnntest:cudnn_8.8.0.121:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.0_cudnn_8.8.0.121_torch
    extends: .pycudnntest:template
    dependencies: ["build:cudnn_8.8.0.121: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.8.0.121: [Hopper]"]

build:cudnn_8.9.2.31:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_cudnn_8.9.2.31_torch
    stage: build
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends: .build:template

test:cudnn_8.9.2.31:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_cudnn_8.9.2.31_torch
    extends: .test:template
    dependencies: ["build:cudnn_8.9.2.31: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.9.2.31: [Ampere]"]

pytest:cudnn_8.9.2.31:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_cudnn_8.9.2.31_torch
    extends: .pytest:template
    dependencies: ["build:cudnn_8.9.2.31: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.9.2.31: [Ampere]"]

pycudnntest:cudnn_8.9.2.31:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_cudnn_8.9.2.31_torch
    extends: .pycudnntest:template
    dependencies: ["build:cudnn_8.9.2.31: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.9.2.31: [Ampere]"]

test:cudnn_8.9.2.31:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_cudnn_8.9.2.31_torch
    extends: .test:template
    dependencies: ["build:cudnn_8.9.2.31: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.9.2.31: [Hopper]"]

pytest:cudnn_8.9.2.31:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_cudnn_8.9.2.31_torch
    extends: .pytest:template
    dependencies: ["build:cudnn_8.9.2.31: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.9.2.31: [Hopper]"]

pycudnntest:cudnn_8.9.2.31:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_cudnn_8.9.2.31_torch
    extends: .pycudnntest:template
    dependencies: ["build:cudnn_8.9.2.31: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.9.2.31: [Hopper]"]

build:cudnn_8.9_clang:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1.0_cudnn_8.9.0.132_clang
    stage: build
    extends: .build:template

build:cudnn_8.9.3_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_torch
    stage: build
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn:template
        - .build:template

test:cudnn_8.9.3_latest:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_torch
    extends:
        - .fetch_cudnn:template
        - .test:template
    dependencies: ["build:cudnn_8.9.3_latest: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.9.3_latest: [Ampere]"]

pytest:cudnn_8.9.3_latest:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_torch
    extends:
        - .fetch_cudnn:template
        - .pytest:template
    dependencies: ["build:cudnn_8.9.3_latest: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.9.3_latest: [Ampere]"]

pycudnntest:cudnn_8.9.3_latest:Ampere:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_torch
    extends:
        - .fetch_cudnn:template
        - .pycudnntest:template
    dependencies: ["build:cudnn_8.9.3_latest: [Ampere]"]
    tags:
        - Ampere
    needs:
        - ["build:cudnn_8.9.3_latest: [Ampere]"]

test:cudnn_8.9.3_latest:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_torch
    extends:
        - .fetch_cudnn:template
        - .test:template
    dependencies: ["build:cudnn_8.9.3_latest: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.9.3_latest: [Hopper]"]

pytest:cudnn_8.9.3_latest:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_torch
    extends:
        - .fetch_cudnn:template
        - .pytest:template
    dependencies: ["build:cudnn_8.9.3_latest: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.9.3_latest: [Hopper]"]

pycudnntest:cudnn_8.9.3_latest:Hopper:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cuda_12.1_torch
    extends:
        - .fetch_cudnn:template
        - .pycudnntest:template
    dependencies: ["build:cudnn_8.9.3_latest: [Hopper]"]
    tags:
        - Hopper
    needs:
        - ["build:cudnn_8.9.3_latest: [Hopper]"]
