default:
    interruptible: true

variables:
  JFROG_API_KEY: $JFROG_API_KEY
  THUNDER_BRANCH_NAME: "main"

before_script:
    - nvidia-smi
    - echo "CUDA_VERSION=$CUDA_VERSION"
    - echo "CUDNN_VERSION=$CUDNN_VERSION"
    
include:
#   - local: ci/job-template.yml
#     inputs:
#         cuda_version: "11.7.1"
#         cudnn_version: "8.5.0.96"
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "schedule"
        
  - local: ci/job-template.yml
    inputs:
        cuda_version: "11.8.0"
        cudnn_version: "8.6.0.163"
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"
        
  - local: ci/job-template.yml
    inputs:
        cuda_version: "11.8.0"
        cudnn_version: "8.7.0.84"
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"
        
  - local: ci/job-template.yml
    inputs:
        cuda_version: "12.0.1"
        cudnn_version: "8.8.1.3"
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"
        
  - local: ci/job-template.yml
    inputs:
        cuda_version: "12.1.0"
        cudnn_version: "8.9.2.26"
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"

  - local: ci/job-template.yml
    inputs:
        cuda_version: "12.2.2"
        cudnn_version: "8.9.5.29"
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"

  - local: ci/job-template.yml
    inputs:
        cuda_version: "12.2.2"
        cudnn_version: "8.9.7.29"


stages:
    - analysis
    - build
    - cpp_tests
    - python_tests
    - pycudnnTest
    - L4_graph_runner
    - notebooks
    - thunder
        
.fetch_cudnn_v9:template:
    before_script:
        - BASE_URL=https://urm.nvidia.com/artifactory/hw-cudnn-generic/CUDNN/v9.0_cuda_12.3/
        - LATEST_DATE_TIME=`curl -S $BASE_URL 2> /dev/null | grep "9.0.0" | grep href |  awk -F\  '{print $3, $4}' | sort -n -t- -k3,3 -k2,2M -k1,1n | tail -1`
        - LATEST_VER=`curl -S $BASE_URL 2> /dev/null | grep "$LATEST_DATE_TIME" | awk -F'["/]' '{print $2}'`
        - echo ${LATEST_DATE_TIME} ${LATEST_VER} ${BASE_URL}${LATEST_VER}/debug_cudnn-linux-x86_64-${LATEST_VER}.tar.gz
        - wget -q --password ${JFROG_API_KEY} ${BASE_URL}${LATEST_VER}/debug_cudnn-linux-x86_64-${LATEST_VER}.tar.gz -O cudnn.tar.gz
        - tar xvf cudnn.tar.gz --directory /
        - export CUDNN_PATH=/debug_cudnn

.build:template:
    script:
        - ci/build.sh
    # keep the build directory so that later jobs can use it
    artifacts:
        paths:
            - build/

.test:template:
    stage: cpp_tests
    script:
        - ci/run_cpp_tests.sh
    # Upload test report to gitlab
    artifacts:
        when: always
        reports:
            junit: build/result-junit.xml
        expire_in: 1 week

.pytest:template:
    stage: python_tests
    script:
        - ci/run_python_tests.sh

.pycudnntest:template:
    stage: pycudnnTest
    script:
        - ci/run_pycudnntest.sh

.L4_graph_runner:template:
    stage: L4_graph_runner
    script:
        - ci/run_L4_graph_runner.sh
        
.thunder:template:
    stage: thunder
    script:
        - git clone https://vedaanta-nvidia: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@github.com/Lightning-AI/lightning-thunder.git
        - cd lightning-thunder
        - git checkout ${THUNDER_BRANCH_NAME}
        - python setup.py develop
        - pytest thunder/tests/test_cudnn_executor.py -v
    allow_failure: true

.L4_graph_runner_large:template:
    stage: L4_graph_runner
    script:
        - ci/run_L4_streams.sh

analysis:clang-format:
    image: ubuntu:jammy
    stage: analysis
    before_script:
        - apt-get update
        - apt-get install -y git clang-format
    allow_failure: true
    script:
        - ci/run_style_check_diff.sh
        
analysis:check-relative-includes:
    image: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04
    stage: analysis
    script:
        - echo "#include \"$CI_PROJECT_DIR/include/cudnn_frontend.h\"" > test_build.cpp
        - echo 'int main() { return 0; }' >> test_build.cpp
        - g++ -o test_build test_build.cpp -std=c++17 -I/usr/local/cuda/include/ -L/usr/lib/x86_64-linux-gnu/ -lcudnn

build:cudnn_9.0.0_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.3.1
    needs: []
    stage: build
    extends:
        - .fetch_cudnn_v9:template
        - .build:template

test:cudnn_9.0.0_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.3.1
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_v9:template
        - .test:template
    needs: ["build:cudnn_9.0.0_latest"]
    
pytest:cudnn_9.0.0_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.3.1
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_v9:template
        - .pytest:template
    needs: ["build:cudnn_9.0.0_latest"]
    resource_group: memory_heavy_${ARCH}
    
pycudnntest:cudnn_9.0.0_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.3.1
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_v9:template
        - .pycudnntest:template
    needs: ["build:cudnn_9.0.0_latest"]
    
L4_graph_runner:cudnn_9.0.0_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.3.1
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_v9:template
        - .L4_graph_runner:template
    needs: ["build:cudnn_9.0.0_latest"]
    
L4_graph_runner_large:cudnn_9.0.0_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.3.1
    parallel:
        matrix:
            - ARCH: ["Ampere", "Hopper"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_v9:template
        - .L4_graph_runner_large:template
    needs: ["build:cudnn_9.0.0_latest"]
    only:
        - schedules

thunder:cudnn_8.9.5.29:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:lightning-py3.10-cuda12.1.1
    needs: []
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    before_script:
        - apt update
        - apt upgrade -y --allow-change-held-packages libcudnn8=8.9.5.29-1+cuda12.2 libcudnn8-dev=8.9.5.29-1+cuda12.2
        - CMAKE_BUILD_PARALLEL_LEVEL=16 pip install . -v
    extends:
        - .thunder:template

analysis:cudnn_clang_disable_exception:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.3.1
    needs: []
    stage: analysis
    script:
        - apt-get update && apt-get install -y clang
        - !reference [.fetch_cudnn_v9:template, before_script]
        - mkdir build && cd build
        - CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -DCMAKE_CXX_FLAGS="-DNV_CUDNN_DISABLE_EXCEPTION" ../
        - cmake --build . -j16 --verbose
        
analysis:cudnn_v9_no_half_conversion:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_8.9.7.29_12.2.2
    needs: []
    stage: analysis
    script:
        - mkdir build && cd build
        - cmake -DCMAKE_CXX_FLAGS="-D__CUDA_NO_HALF_CONVERSIONS__" ../
        - cmake --build . -j16 --verbose
    
analysis:cudnn_clang:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.3.1
    needs: []
    stage: analysis
    script:
        - apt-get update && apt-get install -y clang
        - !reference [.fetch_cudnn_v9:template, before_script]
        - mkdir build && cd build
        - CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake ../
        - cmake --build . -j16 --verbose
    
build:cudnn_8.9_windows:
    tags:
        - Windows
    needs: []
    stage: build
    script:
        # Enable below lines to fetch latest cudnn if needed,
        # Otherwise just use already downloaded cudnn_8.9.5.29
        # - wget https://urm.nvidia.com/artifactory/hw-cudnn-generic/CUDNN/v8.9_cuda_12.2/8.9.5.29/cudnn-windows-x86_64-8.9.5.29.zip -O cudnn.zip
        # - Expand-Archive .\cudnn.zip
        - $Env:CUDNN_PATH = "C:\Users\Public\Downloads\cudnn"
        - mkdir build
        - cd build
        - cmake ../
        - cmake --build . -j16 --verbose

notebooks:cudnn_9.0.0_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.3.1
    stage: notebooks
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    script:
        - !reference [.fetch_cudnn_v9:template, before_script]
        - pip install -v .
        - jupyter execute samples/python/*
    needs: []