default:
    interruptible: true

before_script:
    - nvidia-smi
    - echo "CUDA_VERSION=$CUDA_VERSION"
    - echo "CUDNN_VERSION=$CUDNN_VERSION"

include:
#   - local: ci/job-template.yml
#     inputs:
#         cuda_version: "11.7.1"
#         cudnn_version: "8.5.0.96"
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "schedule"
        
  - local: ci/job-template.yml
    inputs:
        cuda_version: "11.8.0"
        cudnn_version: "8.6.0.163"
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"
        
#   - local: ci/job-template.yml
#     inputs:
#         cuda_version: "11.8.0"
#         cudnn_version: "8.7.0.84"
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "schedule"
        
#   - local: ci/job-template.yml
#     inputs:
#         cuda_version: "12.0.1"
#         cudnn_version: "8.8.1.3"
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "schedule"
        
#   - local: ci/job-template.yml
#     inputs:
#         cuda_version: "12.1.0"
#         cudnn_version: "8.9.2.26"
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "schedule"

#   - local: ci/job-template.yml
#     inputs:
#         cuda_version: "12.2.2"
#         cudnn_version: "8.9.5.29"
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "schedule"

  - local: ci/job-template.yml
    inputs:
        cuda_version: "12.2.2"
        cudnn_version: "8.9.7.29"
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"

  - local: ci/job-template.yml
    inputs:
        cuda_version: "12.3.1"
        cudnn_version: "9.0.0.312"
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"

#   - local: ci/job-template.yml
#     inputs:
#         cuda_version: "12.4.0"
#         cudnn_version: "9.1.0.70"
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "schedule"

  - local: ci/job-template.yml
    inputs:
        cuda_version: "12.5.0"
        cudnn_version: "9.2.1.18"

  - local: ci/job-template.yml
    inputs:
        cuda_version: "12.5.1"
        cudnn_version: "9.3.0.75"

stages:
    - analysis
    - build
    - cpp_tests
    - python_tests
    - pycudnnTest
    - L4_graph_runner
    - unit_tests
    - notebooks
    - thunder
    - deploy
        
.fetch_cudnn_dev:template:
    before_script:
        - BASE_URL=https://urm.nvidia.com/artifactory/hw-cudnn-generic/CUDNN/v9.5_cuda_12.6/
        - LATEST_DATE_TIME=`curl -S $BASE_URL 2> /dev/null | grep "9.5.0" | grep href |  awk -F\  '{print $3, $4}' | sort -n -t- -k3,3 -k2,2M -k1,1n | tail -1`
        - LATEST_VER=`curl -S $BASE_URL 2> /dev/null | grep "$LATEST_DATE_TIME" | awk -F'["/]' '{print $2}'`
        - echo ${LATEST_DATE_TIME} ${LATEST_VER} ${BASE_URL}${LATEST_VER}/debug_cudnn-linux-x86_64-${LATEST_VER}.tar.gz
        - wget -q --password ${JFROG_API_KEY} ${BASE_URL}${LATEST_VER}/debug_cudnn-linux-x86_64-${LATEST_VER}.tar.gz -O cudnn.tar.gz
        - tar xvf cudnn.tar.gz --directory /
        - export CUDNN_PATH=/debug_cudnn # This is required for source building FE
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/debug_cudnn/lib64 # This is required for dlopening BE
  
.fetch_cudnn_rel:template:
    before_script:
        - BASE_URL=https://urm.nvidia.com/artifactory/hw-cudnn-generic/CUDNN/v9.4_cuda_12.6/
        - LATEST_DATE_TIME=`curl -S $BASE_URL 2> /dev/null | grep "9.4.0" | grep href |  awk -F\  '{print $3, $4}' | sort -n -t- -k3,3 -k2,2M -k1,1n | tail -1`
        - LATEST_VER=`curl -S $BASE_URL 2> /dev/null | grep "$LATEST_DATE_TIME" | awk -F'["/]' '{print $2}'`
        - echo ${LATEST_DATE_TIME} ${LATEST_VER} ${BASE_URL}${LATEST_VER}/debug_cudnn-linux-x86_64-${LATEST_VER}.tar.gz
        - wget -q --password ${JFROG_API_KEY} ${BASE_URL}${LATEST_VER}/debug_cudnn-linux-x86_64-${LATEST_VER}.tar.gz -O cudnn.tar.gz
        - tar xvf cudnn.tar.gz --directory /
        - export CUDNN_PATH=/debug_cudnn # This is required for source building FE
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/debug_cudnn/lib64 # This is required for dlopening BE

.build:template:
    script:
        - ci/build.sh
    # keep the build directory so that later jobs can use it
    artifacts:
        paths:
            - build/

.test:template:
    stage: cpp_tests
    script:
        - ci/run_cpp_tests.sh
    # Upload test report to gitlab
    artifacts:
        when: always
        reports:
            junit: build/result-junit.xml
        expire_in: 1 week

.pytest:template:
    stage: python_tests
    script:
        - ci/run_python_tests.sh

.pycudnntest:template:
    stage: pycudnnTest
    script:
        - ci/run_pycudnntest.sh

.unit_tests:template:
    stage: unit_tests
    script:
        - ci/run_unit_tests.sh

.notebooks:template:
    stage: notebooks
    script:
        - pip install -v .
        - ci/run_notebooks.sh

.L4_graph_runner:template:
    stage: L4_graph_runner
    script:
        - ci/run_L4_graph_runner.sh

.L4_graph_runner_large:template:
    stage: L4_graph_runner
    script:
        - ci/run_L4_streams.sh

deploy:build_bdist_wheels:
    tags:
        - wheel_builder
    needs: []
    stage: deploy
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:pip_wheels_cuda_12.4_cudnn_9.3.0
    script:
        - ci/build_pip_wheels.sh
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
    artifacts:
        paths:
            - many_linux_wheels/*.whl

deploy:test_bdist_wheels_8.9.7_3.10:
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    needs: ["deploy:build_wheels"]
    stage: deploy
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_8.9.7.29_12.2.2
    needs: ["deploy:build_bdist_wheels"]
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
    script:
        - apt-get update
        - apt-get install -y software-properties-common
        - add-apt-repository ppa:deadsnakes/ppa
        - apt-get update
        - apt-get -y install python3.10 python3-pip python3.10-distutils
        - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 2
        - update-alternatives --install /usr/bin/python python /usr/bin/python3.10 2
        - pip uninstall -y nvidia_cudnn_frontend
        - pip install -v --find-links many_linux_wheels/ nvidia_cudnn_frontend
        - pip install -r /tmp/requirements.txt
        - pip uninstall -y nvidia-cudnn-cu12 # Only removing it because the test is meant for 8907
        - pytest test/python_fe -n 4 --tb=short

deploy:test_bdist_wheels_9.2.0_3.10:
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    needs: ["deploy:build_wheels"]
    stage: deploy
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_9.2.0.82_12.4.0
    needs: ["deploy:build_bdist_wheels"]
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
    script:
        - apt-get update
        - apt-get install -y software-properties-common
        - add-apt-repository ppa:deadsnakes/ppa
        - apt-get update
        - apt-get -y install python3.10 python3-pip python3.10-distutils
        - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 2
        - update-alternatives --install /usr/bin/python python /usr/bin/python3.10 2
        - pip uninstall -y nvidia_cudnn_frontend
        - pip install -v --find-links many_linux_wheels/ nvidia_cudnn_frontend
        - pip install -r /tmp/requirements.txt
        - pip uninstall -y nvidia-cudnn-cu12 # Only removing it because the test is meant for 8907
        - pytest test/python_fe -n 4 --tb=short

analysis:clang-format:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.3.1
    stage: analysis
    allow_failure: true
    script:
        - ci/run_style_check_diff.sh
        
analysis:check-relative-includes:
    image: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04
    stage: analysis
    script:
        - echo "#include \"$CI_PROJECT_DIR/include/cudnn_frontend.h\"" > test_build.cpp
        - echo 'int main() { return 0; }' >> test_build.cpp
        - g++ -o test_build test_build.cpp -std=c++17 -I/usr/local/cuda/include/ -L/usr/lib/x86_64-linux-gnu/ -lcudnn

analysis:check-CUDNN_FRONTEND_SKIP_JSON_LIB:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_9.1.0.70_12.4.0
    stage: analysis
    script:
        - ci/build_wo_json.sh

build:cudnn_dev_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    needs: []
    stage: build
    extends:
        - .fetch_cudnn_dev:template
        - .build:template

test:cudnn_dev_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_dev:template
        - .test:template
    needs: ["build:cudnn_dev_latest"]
    
pytest:cudnn_dev_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_dev:template
        - .pytest:template
    needs: ["build:cudnn_dev_latest"]
    resource_group: memory_heavy_${ARCH}
    
pycudnntest:cudnn_dev_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_dev:template
        - .pycudnntest:template
    needs: ["build:cudnn_dev_latest"]

unit_tests:cudnn_dev_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_dev:template
        - .unit_tests:template
    needs: ["build:cudnn_dev_latest"]
    
L4_graph_runner:cudnn_dev_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_dev:template
        - .L4_graph_runner:template
    needs: ["build:cudnn_dev_latest"]
    
L4_graph_runner_large:cudnn_dev_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    parallel:
        matrix:
            - ARCH: ["Ampere", "Hopper"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_dev:template
        - .L4_graph_runner_large:template
    needs: ["build:cudnn_dev_latest"]
    only:
        - schedules

build:cudnn_rel_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    needs: []
    stage: build
    extends:
        - .fetch_cudnn_rel:template
        - .build:template

test:cudnn_rel_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_rel:template
        - .test:template
    needs: ["build:cudnn_rel_latest"]
    
pytest:cudnn_rel_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_rel:template
        - .pytest:template
    needs: ["build:cudnn_rel_latest"]
    resource_group: memory_heavy_${ARCH}
    
pycudnntest:cudnn_rel_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_rel:template
        - .pycudnntest:template
    needs: ["build:cudnn_rel_latest"]

unit_tests:cudnn_rel_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_rel:template
        - .unit_tests:template
    needs: ["build:cudnn_rel_latest"]
    
L4_graph_runner:cudnn_rel_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_rel:template
        - .L4_graph_runner:template
    needs: ["build:cudnn_rel_latest"]
    
L4_graph_runner_large:cudnn_rel_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    parallel:
        matrix:
            - ARCH: ["Ampere", "Hopper"]
    tags:
        - ${ARCH}
    extends:
        - .fetch_cudnn_rel:template
        - .L4_graph_runner_large:template
    needs: ["build:cudnn_rel_latest"]
    only:
        - schedules

thunder:pjnl_latest:
    image: gitlab-master.nvidia.com:5005/dl/pytorch/update-scripts:pjnl-latest
    stage: thunder
    needs: []
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    script:
        # Install cudnn_frontend
        - cd /opt/cudnn/cudnn_frontend
        - git checkout develop
        - pip install -v .
        # Run cudnnex tests in thunder
        - cd /opt/pytorch/lightning-thunder
        - pytest thunder/tests/test_cudnn_executor.py -v
    only:
        - schedules

analysis:cudnn_clang_disable_exception:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    needs: []
    stage: analysis
    script:
        - apt-get update && apt-get install -y clang
        - !reference [.fetch_cudnn_dev:template, before_script]
        - mkdir build && cd build
        - CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -DCMAKE_CXX_FLAGS="-DNV_CUDNN_DISABLE_EXCEPTION" ../
        - cmake --build . -j16 --verbose
        
analysis:cudnn_v9_no_half_conversion:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_8.9.7.29_12.2.2
    needs: []
    stage: analysis
    script:
        - mkdir build && cd build
        - cmake -DCMAKE_CXX_FLAGS="-D__CUDA_NO_HALF_CONVERSIONS__" ../
        - cmake --build . -j16 --verbose
    
analysis:cudnn_clang:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    needs: []
    stage: analysis
    script:
        - apt-get update && apt-get install -y clang
        - !reference [.fetch_cudnn_dev:template, before_script]
        - mkdir build && cd build
        - CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake ../
        - cmake --build . -j16 --verbose
    
build:cudnn_8.9_windows:
    tags:
        - Windows
    needs: []
    stage: build
    script:
        # Enable below lines to fetch latest cudnn if needed,
        # Otherwise just use already downloaded cudnn_8.9.5.29
        # - wget https://urm.nvidia.com/artifactory/hw-cudnn-generic/CUDNN/v8.9_cuda_12.2/8.9.5.29/cudnn-windows-x86_64-8.9.5.29.zip -O cudnn.zip
        # - Expand-Archive .\cudnn.zip
        - $Env:CUDNN_PATH = "C:\Users\Public\Downloads\cudnn"
        - mkdir build
        - cd build
        - cmake ../
        - cmake --build . -j16 --verbose

notebooks:cudnn_dev_latest:
    image: gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_12.5.0
    stage: notebooks
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    script:
        - !reference [.fetch_cudnn_dev:template, before_script]
        - pip install -v .
        - ci/run_notebooks.sh
    needs: []

"notebooks:cudnn_8.9.5.29_12.2.2":
  image: "gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_8.9.5.29_12.2.2"
  parallel:
    matrix:
      - ARCH: ["Hopper", "Ampere"]
  tags:
    - ${ARCH}
  extends: .notebooks:template
  needs: []

"notebooks:cudnn_9.0.0.312_12.3.1":
  image: "gitlab-master.nvidia.com:5005/cudnn/cudnn_frontend:cudnn_9.0.0.312_12.3.1"
  parallel:
    matrix:
      - ARCH: ["Hopper", "Ampere"]
  tags:
    - ${ARCH}
  extends: .notebooks:template
  needs: []
