# This module ("SQLDB") serves as the Convolution database for logs generated by/for cudnn_run.py
# sqlite3 is used as the base for all databases
# Note that values are provided as '?' due to recommendations from official Python tutorial (https://docs.python.org/2/library/sqlite3.html)
#  - This means values are inserted/retrieved using ('? ? ?', (val_a, val_b, val_c)) instead of ('%s %s %s' % (val_a, val_b, val_c))
# Some helpful terminology:
#  - 'element' or 'elem': The name of a value that can be stored/retrieved from SQLDB.
#  - 'value': The value for a given element; can be either 'real' (integer/float value) or 'text'
import sqlite3
import os

TABLE_NAME = "ConvData"

class Conditional:
    def __init__(self, name, comparator, value):
        self.name = name
        self.comparator = comparator
        self.value = value

    def get_str(self):
        return '"%s"%s?' % (self.name, self.comparator)

    def get_value(self):
        return self.value

def format_name(name):
    return '"%s"' % name

def unformat_name(name):
    return name[1:-1]

def get_array_as_str(array):
    return "\n".join([str(row) for row in array])

# Not intended to be used outside of this file
class SQLDB:
    def __init__(self, file_name, is_writeable=False, elem_names=None, type_names=None):

        if (elem_names == None) and (type_names != None):
            raise Exception("[SQLDB] Not allowed to specify type_names without elem_names")

        if (elem_names != None) and (type_names == None):
            raise Exception("[SQLDB] Not allowed to specify elem_names without type_names")

        if elem_names:
            elem_names = [format_name(elem_name) for elem_name in elem_names]

        self.is_writeable = is_writeable

        self.file_name = file_name

        # Connect to DB
        self.connect_db()

        self.cursor.execute("PRAGMA table_info(ConvData);")
        data = self.cursor.fetchall()

        self.elem_names = [format_name(elem[1]) for elem in data]
        self.type_names = [elem[2] for elem in data]

        # Table exists
         # User has given elem_names & type_names
          # Table elem names & type names don't match; error
          # Table elem names & type names match
         # User has not given elem_names & type_names
          # Set them from table
        # Table does not exist
         # Create it!

        # If table exists
        if len(data) > 0:
             # If user provided elem/types, check that they match
            if elem_names != None:
                if self.elem_names != elem_names:
                    raise Exception("[SQLDB] Incompatible elem names: %s vs %s" % (str(self.elem_names), str(elem_names)))

                if self.type_names != type_names:
                    raise Exception("[SQLDB] Incompatible type names: %s vs %s" % (str(self.type_names), str(type_names)))

        # If table does not exist
        else:
            self.elem_names = elem_names
            self.type_names = type_names

            self.create_table()

        # Map for element to index in insertion
        self.elem_idx_map  = {}

        # Fill all maps for all elements
        for elem_name in self.elem_names:
            self.elem_idx_map[elem_name] = len(self.elem_idx_map)

        # Get count of all elements
        self.elem_count    = len(self.elem_names)

        # Adding requires a string of '?' for each element
        self.qmarks_str = ",".join(['?'] * self.elem_count)

    def get_elem_names(self):
        return [s[1:-1] for s in self.elem_names]

    def get_type_names(self):
        return self.type_names

    def delete(self):
        if not self.is_writeable:
            raise Exception("[SQLDB] Unable to call \"delete\" on non-writeable SQLDB")

        if os.path.exists(self.file_name):
            os.remove(self.file_name)

    def reset(self):
        if not self.is_writeable:
            raise Exception("[SQLDB] Unable to call \"reset\" on non-writeable SQLDB")

        # Close connections
        self.close()

        # Delete old file
        self.delete()

        # Connect to new DB
        self.connect_db()

        # Create necessary table
        self.create_table()

    def connect_db(self):
        # Create/Load database
        self.conn = sqlite3.connect(self.file_name)

        # Create cursor within database
        self.cursor = self.conn.cursor()

    def create_table(self):
        if not self.is_writeable:
            raise Exception("[SQLDB] Unable to call \"create_table\" on non-writeable SQLDB")

        # Create table string: "groupCount, srcDesc[dimA_0], error_msg"
        table_str = ", ".join(["%s %s" % (elem, type_name) for (elem, type_name) in zip(self.elem_names, self.type_names)])

        # Create table
        self.cursor.execute("CREATE TABLE %s (%s)" % (TABLE_NAME, table_str))

    def add(self, dict_of_elems):
        if not self.is_writeable:
            raise Exception("[SQLDB] Unable to call \"add\" on non-writeable SQLDB")

        # Any unspecified value is assumed to be None
        sqlite_elems = [None] * self.elem_count

        # Loop through all names provided as input
        for elem_name in dict_of_elems:
            # Check if element name exists in maps
            if format_name(elem_name) not in self.elem_idx_map:
                raise Exception("[SQLITE_INTERFACE] Unable to find element \"%s\"" % elem_name)

            # Get index of element (indicates where to store value in array)
            elem_idx = self.elem_idx_map[format_name(elem_name)]

            # Store formatted value in sqlite elems
            sqlite_elems[elem_idx] = dict_of_elems[elem_name]

        # Insert sqlite elems into database
        self.cursor.execute("INSERT INTO %s VALUES (%s)" % (TABLE_NAME, self.qmarks_str), tuple(sqlite_elems))

    def insert_from_db_file_name(self, other_db_file_name):
        self.conn.execute("ATTACH '%s' as dba" % other_db_file_name)

        self.conn.execute("BEGIN")

        self.conn.execute("INSERT INTO %s SELECT * FROM dba.%s" % (TABLE_NAME, TABLE_NAME))

        self.conn.commit()

        self.conn.execute("detach database dba")

    def __str__(self):
        return get_array_as_str(self.get())

    def get_gen(self, retrieve_names=None, conditionals=None, order_by=None):
        # If none, set retrieve names to all names
        if retrieve_names == None:
            retrieve_names = self.elem_names
        else:
            retrieve_names = [format_name(elem_name) for elem_name in retrieve_names]

        # Create ""groupCount","destDesc[dimA_0]"" string
        retrieve_name_str = ",".join(retrieve_names)

        # Initialize conditionals to empty (indicating no conditionals)
        cond_str = ""
        cond_values = []

        # If not none/empty, set conditional strings/values
        if conditionals != None and len(conditionals) > 0:
            # Create "WHERE "groupCount"    >=20 AND " string
            cond_str = "WHERE %s" % " AND ".join([cond.get_str() for cond in conditionals])

            # Get all conditional values
            cond_values = [cond.get_value() for cond in conditionals]

        # Default to blank order by string
        order_str = ""

        if order_by:
            order_str = " ORDER BY %s" % ",".join(format_name(order_by_elem) for order_by_elem in order_by)

        query_str = "SELECT %s FROM %s %s%s" % (retrieve_name_str, TABLE_NAME, cond_str, order_str)

        rows = self.cursor.execute(query_str, cond_values)

        all_results = []

        for row in rows:
            result = {}

            for idx, elem_name in enumerate(retrieve_names):
                result[unformat_name(elem_name)] = row[idx]

            yield result

    def get(self, retrieve_names=None, conditionals=None, order_by=None):
        result = list(self.get_gen(retrieve_names=retrieve_names, conditionals=conditionals, order_by=order_by))

        if len(result) == 0:
            return None

        return result

    def __enter__(self):
        return self

    def commit(self):
        self.conn.commit()

    def close(self):
        self.conn.commit()
        self.conn.close()

    def __exit__(self, exc_type, exc_value, traceback):
        self.close()

if __name__ == "__main__":
    elem_names = ["groupCount", "destDesc.dimA_0", "flags_str"]

    db = SQLDB("SQLDB_TEMP.db", elem_names)
    db.clear()
    db.add({"groupCount":  0, "destDesc.dimA_0": 30, "flags_str": "-groupCount0 -n30"})
    db.add({"groupCount": 10, "destDesc.dimA_0": 20, "flags_str": "-groupCount10 -n20"})
    db.add({"groupCount": 20, "destDesc.dimA_0": 10, "flags_str": "-groupCount20 -n10"})
    db.add({"groupCount": 30, "destDesc.dimA_0": 00, "flags_str": "-groupCount30 -n0"})

    print("Printing entire database using str")
    print(str(db))

    print("\nPrinting entire database using default get")
    print(get_array_as_str(db.get()))

    print("\nPrinting only groupCount >= 20")
    print(get_array_as_str(db.get(["groupCount", "flags_str"], [Conditional("groupCount", ">=", 20)])))

    print("\nPrinting only groupCount >= 20 AND destDesc.dimA_0 < 10")
    print(get_array_as_str(db.get(["groupCount", "destDesc.dimA_0", "flags_str"], [Conditional("groupCount", ">=", 20), Conditional("destDesc.dimA_0", "<", 10)])))

    print("\nPrint entire database sorted by groupCount")
    print(get_array_as_str(db.get(None, None, "groupCount")))

    print("\nPrint entire database sorted by destDesc.dimA_0")
    print(get_array_as_str(db.get(None, None, "destDesc.dimA_0")))

    import os

    os.remove("SQLDB_TEMP.db")
