#!/usr/bin/python3 -u

# Merge the new_api_dbs generated by the jobs from query and diff stage

import sys
import argparse
import re
import os
import time

from heur_diff_utility import PeresistentSQLDB, FlagApiIndexer, remove_existing_shelve_db

parser = argparse.ArgumentParser(
    description='')
parser.add_argument('-args_file_path', '--args_file_path',
                    metavar='args_file_path',
                    dest='args_file_path',
                    required=True,
                    help='Specify the tmp file that stores the pair of file to merge.')
args = parser.parse_args()

start_time = time.time()

# ***********************************************
# extract necessary info from the args
# ***********************************************

# get partition idx from tmp file name
partition_idx = os.path.basename(args.args_file_path).split(".")[0].split("_")[-1]

# parse the partition info
api_db_paths = ""
with open(args.args_file_path, "r") as tmp_file:
    api_db_paths = tmp_file.read().split(",")

assert len(api_db_paths) == 2
db_path_1 = api_db_paths[0]
db_path_2 = api_db_paths[1]


# ***********************************************
# perform the merging
# ***********************************************

if not os.path.exists(db_path_1) and not os.path.exists(db_path_2):
    print("None of %s and %s exist: " % (db_path_1, db_path_2))

elif os.path.exists(db_path_1) and not os.path.exists(db_path_2):
    print("Not exist: ", db_path_2)

elif not os.path.exists(db_path_1) and os.path.exists(db_path_2):

    # rename `db_path_2` to `db_path_1`
    print("Not exist: ", db_path_2)
    print("Renaming %s to %s" % (db_path_2, db_path_1))
    os.rename(db_path_2, db_path_1)

else:

    print("Merging %s and %s" % (db_path_1, db_path_2))

    # tracking idx change in db_2
    old_idx_to_new_idx = {}

    # the new items to be added to db1
    db_1_to_add = {}

    idx_table_db_1 = PeresistentSQLDB(db_path_1, "idx_table",
                       elem_names=["idx", "val"],
                       type_names=["INTEGER PRIMARY KEY", "TEXT"], load_to_mem=False, mode='r')
    if idx_table_db_1.is_table_exist():
        old_indexer_1 = FlagApiIndexer()
        key_to_index = {}
        index_to_key = {}
        for row in idx_table_db_1.get_gen(["idx", "val"]):
            key_to_index[row["val"]] = int(row["idx"])
            index_to_key[int(row["idx"])] = row["val"]
        old_indexer_1.load(key_to_index, index_to_key)
    else:
        idx_table_db_1.close()
        raise RuntimeError("no indexer in %s" % db_path_1)
    idx_table_db_1.close()

    idx_table_db_2 = PeresistentSQLDB(db_path_2, "idx_table",
                       elem_names=["idx", "val"],
                       type_names=["INTEGER PRIMARY KEY", "TEXT"], load_to_mem=False, mode='r')
    if idx_table_db_2.is_table_exist():
        old_indexer_2 = FlagApiIndexer()
        key_to_index = {}
        index_to_key = {}
        for row in idx_table_db_2.get_gen(["idx", "val"]):
            key_to_index[row["val"]] = int(row["idx"])
            index_to_key[int(row["idx"])] = row["val"]
        old_indexer_2.load(key_to_index, index_to_key)
    else:
        idx_table_db_2.close()
        raise RuntimeError("no indexer in %s" % db_path_2)
    idx_table_db_2.close()

    db_2_sqlite = PeresistentSQLDB(db_path_2, "ConvData",
                       elem_names=["flag_idx", "api_list"],
                       type_names=["TEXT PRIMARY KEY", "TEXT"], load_to_mem=False, mode='r')

    # load db_2 to memory
    start_time = time.time()
    db_2 = {}
    for row in db_2_sqlite.get_gen(["flag_idx", "api_list"]):
        db_2[row["flag_idx"]] = tuple(row["api_list"].split(","))
    db_2_sqlite.close()
    print("loaded db to memory: %s, time: %s seconds" % (db_path_2, (time.time() - start_time)))


    pattern_idx = re.compile(r'^\[(\d+)\]$')
    key_count = 0
    db_2_len = len(db_2.keys()) -2
    loop_start = time.time()

    # sweep, build old_idx_to_new_idx, and replace idx
    for flag in db_2:
        if flag == "#indexer":
            continue

        key_count += 1
        if (key_count % 100000 == 0):
            print("[%s] traversed %d/%d, %s seconds" % (db_path_2, key_count, db_2_len, (time.time() - loop_start)))
            loop_start = time.time()

        start_time = time.time()

        # replace flag indices from indexer_2 to indexer_1
        flag_idx_list = flag.split(",")
        current_idx = 0
        while current_idx < len(flag_idx_list):
            if pattern_idx.match(flag_idx_list[current_idx]):
                index = int(pattern_idx.match(
                    flag_idx_list[current_idx]).groups()[0])
                flag_str = old_indexer_2.get_key_by_index(index)
                flag_idx_list[current_idx] = "[%d]" % old_indexer_1.get_key_index(flag_str)
            current_idx += 1

        new_flag_idx = ",".join(flag_idx_list)

        # replace api indices from indexer_2 to indexer_1
        idx_tuple = db_2[flag]
        idx_list = list(idx_tuple)
        current_idx = 0
        while current_idx < len(idx_list):

            # if this is an index
            if pattern_idx.match(idx_list[current_idx]):
                index = int(pattern_idx.match(idx_list[current_idx]).groups()[0])
                api_str = old_indexer_2.get_key_by_index(index)
                idx_list[current_idx] = "[%d]" % old_indexer_1.get_key_index(api_str)
            current_idx += 1
        
        # write new item to db_1 (in mem)
        db_1_to_add[new_flag_idx] = tuple(idx_list)

    # write updated indexer 1 back to sqlite db 1
    idx_table_db_1 = PeresistentSQLDB(db_path_1, "idx_table",
                    elem_names=["idx", "val"],
                    type_names=["INTEGER PRIMARY KEY", "TEXT"], load_to_mem=False, mode='w')
    key_to_index_dict = old_indexer_1.get_key_to_index_dict()
    for key in key_to_index_dict:
        idx_table_db_1.replace({"idx": key_to_index_dict[key], "val": key})
    idx_table_db_1.close()


    print("start writing to sqlite: %s" % (db_path_1))
    start_time = time.time()
    db_1_sqlite = PeresistentSQLDB(db_path_1, "ConvData",
                       elem_names=["flag_idx", "api_list"],
                       type_names=["TEXT PRIMARY KEY", "TEXT"], load_to_mem=False, mode='w')
    for key in db_1_to_add:
        db_1_sqlite.add({"flag_idx": key, "api_list": ",".join(list(db_1_to_add[key]))})
    print("%s: size: %s" % (db_path_1, db_1_sqlite.estimate_size()))
    db_1_sqlite.close()
    
    print("save db_1 to sqlite: %s, time: %s seconds" % (db_path_1, (time.time() - start_time)))

    remove_existing_shelve_db(db_path_2)